[package]
name = "wordguess"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
debug_print = "1.0.0"
rand = "0.8.5"
serde = "1.0.193"
toml = "0.8.8"
utf8_slice = "1.0.0"
